import { Inter } from "next/font/google";
import "./globals.scss";
// import TransitionProvider from "@/components/transitionProvider";
import Header from "@/components/Header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <TransitionProvider> */}

        <Header />
        {children}
        {/* </TransitionProvider> */}
      </body>
    </html >
  );
}
